### ISSUE TITLE
Exclude Tag from Cloud

### ISSUE THREAD

**Issue by vnwds** [BeAPI/simple-tags#100]
Hi!

I am trying to exclude a specific tag from the tag cloud. I tried using the string 'exclude' => '1703' in the Advanced Usage text box but that did not work.

From the documentation this looks possible and like what I would use. What am I missing?

Thanks!

**Comment by herewithme** [comment]
Try this format :
<img width="733" alt="Capture d’écran 2019-05-10 à 06 02 57" src="https://user-images.githubusercontent.com/898608/57502684-18c6ad00-72ed-11e9-896f-0ecc9e9d78e0.png">
<img width="455" alt="Capture d’écran 2019-05-10 à 06 04 12" src="https://user-images.githubusercontent.com/898608/57502685-18c6ad00-72ed-11e9-84f8-89e2ae6cef69.png">

Reopen if you need.
