### ISSUE TITLE
Feature Request: "singleonly" for auto-link

### ISSUE THREAD

**Issue by ezraimanuel** [BeAPI/simple-tags#113]
Hello!

Can you add option "`singleonly`" for Auto link? it would be nice since other features has that option.

for now I manually changed `is_singular()` to `is_single()` in `simple-tags/inc/class.client.autolinks.php` file after update.

thank you! #

**Comment by herewithme** [comment]
Hey,

Thanks for report.

Added on:
https://github.com/BeAPI/simple-tags/commit/6ec881c25a64688d186a3de7901e95dfd7ab583b#diff-350a20a051d777298dc7ed049a5c4c9cR225
