### ISSUE TITLE
Spelling mistake: "Link subtition" 

### ISSUE THREAD

**Issue by justingit** [BeAPI/simple-tags#127]
Here's the string that needs to be fixed: 

`Exclude some terms from tag link. For Ads Link subtition
`

This string shows up in a few parts of the app. "**subtition**" should be, "**substitution**"

**Comment by herewithme** [comment]
Thanks ! https://github.com/BeAPI/simple-tags/commit/9c6e8a4666f0cbb64b27abc7798d9bc7966499be
