### ISSUE TITLE
Different tags for different languages

### ISSUE THREAD

**Issue by BekirFaruk** [BeAPI/simple-tags#31]
Hi, i have a website which is using 3 languages. I would like to show my tags in current language. for example, 

http://domainname.com/en/content
tags: price

http://domainname.com/de/content
tags: preis

(I am using qTranslate for multilangual contents.) 

Do you have any opinion to achive this ?

Thanks a lot.

**Comment by herewithme** [comment]
No, I do not have a solution.
And I do not propose compatibility for this plugin (Q-Translate).
