### ISSUE TITLE
Cloud display bug

### ISSUE THREAD

**Issue by Guver13** [BeAPI/simple-tags#34]
Hi,

I'm having an issue with the plugin, the cloud in not displaying correctly.
Image attached.
![st_plugin](https://cloud.githubusercontent.com/assets/5180394/6246832/c298db6a-b775-11e4-98dc-9ee9c22ede25.png)

Thanks

**Comment by herewithme** [comment]
It's a CSS problem, strongly related to your theme.

There is no generic solution.
