### ISSUE TITLE
Tag Cloud Appears Twice

### ISSUE THREAD

**Issue by Aldrich0102** [BeAPI/simple-tags#35]
On my blog, the tag cloud below the post shows up 2 times, right on top of the other. I have tried to figure this out, but I need help. You can see what I am saying by going to my blog and click any post.

That website is: http://hashtagNewburgh.com

If anyone can help me, I would sincerely appreciate it.

Thanks so much,

Brian Aldrich

**Comment by Sophist-UK** [comment]
I have this same problem. I suspect that the `the_content filter` in class.client.post_tags.php is being called twice for the same post.

**Comment by herewithme** [comment]
In my opinion, it's not really a plugin bug, but hey, it's fixed.
