### ISSUE TITLE
ST AJAX API showing no results

### ISSUE THREAD

**Issue by leesei** [BeAPI/simple-tags#48]
I've been using ST on multiple WP installations with Bitnami Stack but it failed to work on a Windows Server 2008 machine. The Click Tags and auto suggest in the Tags widget in New Post page will always show no result.

Then I found that this AJAX API is returning 0 bytes instead of the JSON for the tags in my WP site:
[http://localhost:8080/wordpress/wp-admin/admin-ajax.php?action=simpletags&stags_action=helper_js_collection](http://localhost:8080/wordpress/wp-admin/admin-ajax.php?action=simpletags&stags_action=helper_js_collection)

Where should I start debugging the issue?

**Comment by herewithme** [comment]
I do not offer support for Windows HTTP servers. Too exotic.

**Comment by leesei** [comment]
FYI, Bitnami Stack uses Apache and not Microsoft's IIS.
Anyway I'm not working on the project anymore and this can be closed.
