### ISSUE TITLE
Suggest tags from the post content

### ISSUE THREAD

**Issue by carlo1998** [BeAPI/simple-tags#50]
Do you have a feature that gets all the words used in the post and then present it as suggestions for tags? It's a good feature to have so that we can just remove all the terms we don't want to include as tags. If there is a feature like this already, can you show me how do I use this?

**Comment by NicolasKulka** [comment]
Shortcode [st-the-tags] and [st_the_tags] is add.

**Comment by herewithme** [comment]
I close because very old ticket.
