### ISSUE TITLE
suggested tags - no local, no yahoo

### ISSUE THREAD

**Issue by ThomasKujawa** [BeAPI/simple-tags#53]
After upgrading to wp4.4 there are no local tags or anything else. :-(

![2015-12-09 16-29-45 screenshot](https://cloud.githubusercontent.com/assets/2462747/11689488/8d1a7016-9e92-11e5-88ab-de52996f8e91.png)

**Comment by fingertrouble** [comment]
Same here...upgrading to 4.4 has killed Simple Tags! Doesn't show the options, only "Choose a provider to get suggested tags (local, yahoo or tag the net)." - I use this plugin all the time, I'm not aware of one that does anything similar, especially that has support for OpenCalais, Alchemy, Zemanta Yahoo et al.

**Comment by designcre8or** [comment]
Same.

**Comment by herewithme** [comment]
Try this ?
http://myonlinesecurity.co.uk/wordpress-4-4-update-breaks-itself-with-ssl-certificate-problem-unable-to-get-local-issuer-certificate/

**Comment by Roachware** [comment]
I can install and update plug-ins, so I seem to have no issue with the SSL as mentioned in the article. Hoewever, even unfolding the widgets (e.g. to get at the clickable tag list) only shoves everything down a line or so, but keeps everything folded up. Especially the suggested tags are an option I sorely miss...

**Comment by NicolasKulka** [comment]
Bug is resolved

**Comment by ThomasKujawa** [comment]
when will the update released?

**Comment by NicolasKulka** [comment]
This week

**Comment by NicolasKulka** [comment]
New release 2.4.4 : https://wordpress.org/plugins/simple-tags/

**Comment by ThomasKujawa** [comment]
Thank you soooo much. !!!
