### ISSUE TITLE
Error when using PHP 7

### ISSUE THREAD

**Issue by mackaaij** [BeAPI/simple-tags#54]
When using PHP 7, I can't reach my WordPress admin but see a blank screen instead. The web server's log showed this error and after disabling the plugin I could use WordPress admin:

Backend fatal error: PHP Fatal error:  Switch statements may only contain one default clause in /public_html/wp-content/plugins/simple-tags/inc/class.admin.php on line 376\n

**Comment by herewithme** [comment]
Fixed on : https://github.com/herewithme/simple-tags/issues/46

Use github version for the moment ?

**Comment by mackaaij** [comment]
Thanks, didn't notice that one because of the title. I'll wait for the official release to re-enable the plugin.

**Comment by NicolasKulka** [comment]
New release 2.4.4 : https://wordpress.org/plugins/simple-tags/

**Comment by mackaaij** [comment]
Works, thanks for the heads up!
