### ISSUE TITLE
file not found on updating to newest version,

### ISSUE THREAD

**Issue by moltra** [BeAPI/simple-tags#55]
Downloading update from https://downloads.wordpress.org/plugin/simple-tags.2.4.3.zip…
An error occurred while updating Simple Tags: Download failed. Not Found

**Comment by NicolasKulka** [comment]
Problem in WordPress.org, but in the meantime download the version 2.4.3 github

https://github.com/BeAPI/simple-tags/archive/2.4.3.zip

**Comment by NicolasKulka** [comment]
Bug is resolved

**Comment by moltra** [comment]
Thank, this was the only way I knew to let you know of the problem on wordpress.org.  

Great Plugin by the way..
