### ISSUE TITLE
array_flip warning - class.client.post_tags.php line 130

### ISSUE THREAD

**Issue by galbaras** [BeAPI/simple-tags#56]
After updating the plugin today to v2.4.4, I'm getting these:

PHP Warning:  array_flip(): Can only flip STRING and INTEGER values! in /home/ronitbaras/public_html/wp-content/plugins/simple-tags/inc/class.client.post_tags.php on line 130

I think get_object_term_cache() and wp_get_object_terms() return arrays of term objects, which cannot be flipped. Maybe array_unique() cannot be avoided here.

**Comment by NicolasKulka** [comment]
Bug is resolved : https://github.com/BeAPI/simple-tags

**Comment by galbaras** [comment]
Will there be a plugin update on wordpress.org soon?

BTW, the github changelog is missing v2.4.4 and the wordpress.org changelog isn't showing it either, although it's the latest version there.

**Comment by NicolasKulka** [comment]
https://wordpress.org/support/plugin/simple-tags 2.4.5
