### ISSUE TITLE
Bug in helper-options.js?

### ISSUE THREAD

**Issue by Subhash-at** [BeAPI/simple-tags#58]
I think there is a bug in **.../simple-tags/assets/js/helper-options.js** on line 8 and 28 which prevents the tabs in administration to work (tested with WP 4.4.1 in Firefox 43.0.4):
`if (typeof(localStorage) != 'undefined') {`
has to be:
`if (typeof(localStorage) != 'undefined' && localStorage != null) {`

**Comment by herewithme** [comment]
Fixed on 
https://github.com/BeAPI/simple-tags/commit/018519b1f2ce1f58ad9a5d671e7a8346cc4cb4ae

Thanks
