### ISSUE TITLE
Simple Tags 2.4.5 not working with WordPress 4.3.1

### ISSUE THREAD

**Issue by Sophist-UK** [BeAPI/simple-tags#59]
In Simple Tags 2.4.5 and WordPress 4.3.1, viewing a single post results in this error:

Warning: Missing argument 2 for get_term() in /wp-includes/taxonomy.php on line 1349

This error repeats once per tag before culminating in:

Catchable fatal error: Object of class WP_Error could not be converted to string in /wp-includes/formatting.php on line 3275

See https://wordpress.org/support/topic/missing-argument-2-for-get_term

**Comment by herewithme** [comment]
ping @NicolasKulka

**Comment by NicolasKulka** [comment]
https://wordpress.org/support/topic/missing-argument-2-for-get_term

**Comment by herewithme** [comment]
Fixed on an older commit.
Thanks for report.
