### ISSUE TITLE
Category cloud

### ISSUE THREAD

**Issue by Neacal** [BeAPI/simple-tags#60]
Hello! Thank you for this plugin.

Using widgets on my posts sidebar I can add tag cloud and category cloud. I also can add [st_tag_cloud] shortcode to show tag cloud on a page. Is there a possibility to add a shortcode for category cloud? Thanks a lot!

**Comment by herewithme** [comment]
Used taxonomy argument !
`[st_tag_cloud taxonomy="category"]`

**Comment by herewithme** [comment]
I close because very old ticket.
