### ISSUE TITLE
Box with autocompletion not showing

### ISSUE THREAD

**Issue by kostek00** [BeAPI/simple-tags#63]
Not long ago I saw that the box with autocompletion stopped showing up. I wasn't submitting new issue because I was gonna reinstall site anyway so it might be compability issue. After fresh wordpress installation Simple Tags was first plugin I installed and it appears it's not plugin compability issue as this was the only plugin. I checked screen settings (is this how it's called in english?) and I saw that "Tags (Simple Tags)" don't have checkbox only text, see attached image.
![bez nazwy-1](https://cloud.githubusercontent.com/assets/6637173/17586669/76293ba6-5fc3-11e6-955e-e9e30a3df1d4.jpg)

**Comment by herewithme** [comment]
This is probably a bug with another plugin because the problem does not occur with a fresh WP installation.

**Comment by kostek00** [comment]
Read again what I wrote:

> After fresh wordpress installation Simple Tags was first plugin I installed and it appears it's not plugin compability issue as this was the only plugin

**Comment by herewithme** [comment]
You are still experiencing the problem with the latest version of WP?

**Comment by kostek00** [comment]
Yes, but you responded too late because today I removed WP completly and changed it for something else.

**Comment by herewithme** [comment]
All right, I'm closing;)
