### ISSUE TITLE
Excluding tags from tag cloud

### ISSUE THREAD

**Issue by pointsi** [BeAPI/simple-tags#71]
I am trying to exclude several tags from the tag cloud, which I am implementing using the shortcode [st_tag_cloud].

In the Tag Cloud tab, under Advanced Usage, I have tried putting in each of the following (separately) without success:

'exclude' => '208',
'exclude=208' 

Do you know how I can fix this issue?

**Comment by herewithme** [comment]
Hey @pointsi 

I just tested the plugin on these points, and I do not have this problem.
<img width="733" alt="Capture d’écran 2019-05-10 à 06 02 57" src="https://user-images.githubusercontent.com/898608/57501905-9f798b00-72e9-11e9-928f-636d59debfb6.png">
<img width="455" alt="Capture d’écran 2019-05-10 à 06 04 12" src="https://user-images.githubusercontent.com/898608/57501906-9f798b00-72e9-11e9-8e10-6376dea1c6c9.png">

Please re-open your issue if required.
