### ISSUE TITLE
Auto Tags not tagging numbers

### ISSUE THREAD

**Issue by avilao** [BeAPI/simple-tags#72]
Hi

If I had a tag with a number (a year for instance) it won't generate an auto tag in the text. Here is a screenshot where 2015 should have been tagged.

![image](https://cloud.githubusercontent.com/assets/9694422/24161044/45deb542-0e5b-11e7-8655-fbd17c4cc753.png)

**Comment by herewithme** [comment]
Fixed on:
https://github.com/BeAPI/simple-tags/commit/504d6df5ad842a7a2f95a3f12c6d77a5610a93ef

Thansk for report.
