### ISSUE TITLE
Trying to get property of non-object in error

### ISSUE THREAD

**Issue by breaktheskyinc** [BeAPI/simple-tags#84]
Hey there, when I assign some descriptive text to my theme's 404 page editor, I end up getting the following error on the page:

[![Screenshot from Gyazo](https://gyazo.com/ee5a24992069231765f4790d6d680244/raw)](https://gyazo.com/ee5a24992069231765f4790d6d680244)

**Comment by herewithme** [comment]
Hello,

Thanks for report.
Fixed here :
https://github.com/BeAPI/simple-tags/commit/00c1a4f4a3bbbe62ef82687715aed363ff2b2d55#diff-7f70f1496a8a77d6a1cb2466a7aba839R137
