### ISSUE TITLE
Accented characters ?

### ISSUE THREAD

**Issue by Titi59** [BeAPI/simple-tags#87]
Hello, first I would like to thank you 'cause it's a great plugin !

Unfortunately, I get some troubles with the french accented characters like é,è,... : the autotag system doesn't work with them...

Could you help me ?

Regards,

**Comment by herewithme** [comment]
Can you give me some examples because it works on my test instance.

<img width="745" alt="Capture d’écran 2019-05-10 à 06 33 30" src="https://user-images.githubusercontent.com/898608/57502783-8e327d80-72ed-11e9-8a5e-e4e6284e3d5b.png">

Please reopen issue if required.
