### ISSUE TITLE
Disable auto tag

### ISSUE THREAD

**Issue by staipa** [BeAPI/simple-tags#89]
Hi! I have a big problem.
For each update of my post, plugin serach and insert automatically tags.
I want to disable this feature and mantain all other feature.
I need to choose each tag time by time.
I tried to remove flag in "Auto terms posts | This feature allow to add automatically terms on a post by proceding to a search into content." but tag is again insert automatically.
What can I do?

Another thing. It can be usefull to insert possibility to set a maximum number of tags automatically inserted from plugin.

Thanks

**Comment by herewithme** [comment]
@staipa you can deactivate this feature from :
https://YOURSITE/wp-admin/tools.php?page=st_auto&taxo=post_tag&cpt=post

Reopen this issue if need.
