### ISSUE TITLE
Undefined property: stdClass::$post_type when adding a Link

### ISSUE THREAD

**Issue by uusijani** [BeAPI/simple-tags#98]
The plugin refers to `$post->post_type` before testing it exists, which triggers an error for WP's built-in (though hidden-by-default since forever) "link" post type. The error appears quite harmless, as it doesn't seem to interfere with the link editor's functionality in any way.

# Setup
* Simple Tags version 2.4.7
* WP version 4.9.8
* PHP version 5.6.33

# Steps to reproduce
1. Set `WP_DEBUG` on (define as `true`)
2. Enable WordPress' link manager (`add_filter( 'pre_option_link_manager_enabled', '__return_true' );`),
3. Go to `Links > Add New`

# What happens
Simple Tags' Settings box in the sidebar shows the following notices:

    Notice: Undefined property: stdClass::$post_type in [path to wp]/wp-content/plugins/simple-tags/inc/class.admin.post.php on line 46
    Notice: Undefined property: stdClass::$post_type in [path to wp]/wp-content/plugins/simple-tags/inc/class.admin.post.php on line 54

**Comment by herewithme** [comment]
Fixed here :
https://github.com/BeAPI/simple-tags/commit/c49136ded0da77783551b4b69cbefa5df110f742#diff-6cd0ea062df542b9cbba2fcc40577f69R42

Thanks for report.
